CGROUP_PATH = "/sys/fs/cgroup"
MEM_UNIT_MAP = {"kb": 1024, "mb": 1024**2, "gb": 1024**3}
LOCAL_IMAGE_REGISTRY = "/home/kalish/Documents/projects/LEARNING/building-docker/codecrafters-docker-python/images"
SESSION_DATA_PATH = "/home/kalish/Documents/projects/LEARNING/building-docker/codecrafters-docker-python/session.json"
DEFAULT_BRIDGE_IP = "172.16.7.0/24"
DEFAULT_BRIDGE_NAME = "dockerclone0" 
CONTAINER_RUNTIME_ROOT_DIR="/home/kalish/Documents/projects/LEARNING/building-docker/codecrafters-docker-python/runtimes"
LAYER_BLOB_PATH="/home/kalish/Documents/projects/LEARNING/building-docker/codecrafters-docker-python/layer_blobs"
EXTRACTED_LAYERS_PATH="/home/kalish/Documents/projects/LEARNING/building-docker/codecrafters-docker-python/extracted_layers"